# GENERAL
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[shell]
program = "zsh"
args = ["--login"]
# args = ["--login", "-c", "tmux new-session -A -s home"]

# ENV
[env]
TERM = "xterm-256color"

# WINDOW
[window]
dimensions = { columns = 0, lines = 0}
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "None"
opacity = 0.85
startup_mode = "Maximized"
dynamic_title = true
option_as_alt = "OnlyLeft"

# SCROLLING
[scrolling]
history = 50000
multiplier = 3

# FONT
[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 16.0
offset = { x = 0, y = 0}
glyph_offset = { x = 0, y = 0}

# COLORS
[colors]
draw_bold_text_with_bright_colors = true

# SELECTION
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>t"
save_to_clipboard = true

# CURSOR
[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true

# MOUSE
[mouse]
hide_when_typing = true
bindings = [
  {mouse = "Middle", mods = "Control", action = "PasteSelection"}
]

# HINTS
[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
mouse = { mods = "Control|Shift", enabled = true }

# KEYBOARD
[keyboard]
bindings = [
  {key = "Equals", mods = "Command", action = "IncreaseFontSize"},
  {key = "Minus", mods = "Command", action = "DecreaseFontSize"},
  {key = "Q", mods = "Command", action = "Quit"},
  {key = "Space", mods = "Control", chars = "\u0000"},
  {key = "P", mods = "Command|Shift", chars = "alacritty -e 'htop' & \r"},
  {key = "I", mods = "Command|Shift", chars = "alacritty -e 'ipython' & \r"},
  {key = "N", mods = "Command", action = "CreateNewWindow"},
]

# DEBUG
[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false
